insert into `motorcycles` (`discontinued`, `id`, `motorcycle_type_id`, `name`) values (0, 1, 1, 'YAMAHA YBR125');
insert into `motorcycles` (`discontinued`, `id`, `motorcycle_type_id`, `name`) values (1, 2, 1, 'BAJAJ DOMINAR 400');
insert into `motorcycles` (`discontinued`, `id`, `motorcycle_type_id`, `name`) values (0, 3, 2, 'Honda CB400SS');
insert into `motorcycles` (`discontinued`, `id`, `motorcycle_type_id`, `name`) values (1, 4, 2, 'Suzuki GSX1300R Hayabusa');
insert into `motorcycles` (`discontinued`, `id`, `motorcycle_type_id`, `name`) values (1, 5, 2, 'Kawasaki Ninja H2 SX');
insert into `motorcycles` (`discontinued`, `id`, `motorcycle_type_id`, `name`) values (0, 6, 3, 'Honda Gold Wing');
insert into `motorcycles` (`discontinued`, `id`, `motorcycle_type_id`, `name`) values (0, 7, 3, 'Планета');
insert into `motorcycles` (`discontinued`, `id`, `motorcycle_type_id`, `name`) values (1, 8, 3, 'KTM Adventure 790');
insert into `motorcycles` (`discontinued`, `id`, `motorcycle_type_id`, `name`) values (0, 9, 1, 'Moto1');
insert into `motorcycles` (`discontinued`, `id`, `motorcycle_type_id`, `name`) values (0, 10, 5, 'Moto2');
insert into `motorcycles` (`discontinued`, `id`, `motorcycle_type_id`, `name`) values (0, 11, 5, 'Moto3');
insert into `motorcycles` (`discontinued`, `id`, `motorcycle_type_id`, `name`) values (1, 12, 6, 'Moto4');
insert into `motorcycles` (`discontinued`, `id`, `motorcycle_type_id`, `name`) values (1, 13, 6, 'Moto5');
insert into `motorcycles` (`discontinued`, `id`, `motorcycle_type_id`, `name`) values (1, 14, 6, 'Moto6');
insert into `motorcycles` (`discontinued`, `id`, `motorcycle_type_id`, `name`) values (0, 15, 9, 'moto-moto-1');
insert into `motorcycles` (`discontinued`, `id`, `motorcycle_type_id`, `name`) values (0, 16, 9, 'moto-moto-2');
insert into `motorcycles` (`discontinued`, `id`, `motorcycle_type_id`, `name`) values (0, 17, 9, 'moto-moto-3');
